# Generated by Django 4.1.5 on 2023-02-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_admin_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='promo_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
