# Generated by Django 4.1.5 on 2023-02-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_member_promo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchased_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('promo_code', models.CharField(max_length=10)),
                ('purchased_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
